

//started code by Y
[name="SNCuts" type="SNCuts"]  

#source_pos_path : string = "/sps/nemo/scratch/ykozina/Falaise/tutorial/CalibrationTools/build/CalibrationCutsModule/source_positions.txt"

#source_pos_path : string = ""

	#useEventHasTwoNegativeParticles : boolean = true
	#useEventHasTwoTracks : boolean = true
	#useEventHasTwoFoilVertices : boolean = true
	#useEventHasTwoCaloHits : boolean = true
	#useEventHasTwoAssociatedCaloHits : boolean = true
	#useEventHasSumEnergyAbove : boolean = true
	minSumEnergy : real = 0.0
	#useEventHasSumEnergyBelow : boolean = true
	maxSumEnergy : real = 3500.0
	
	
	useEventHasVertexCloseToCalibSource : boolean = true
	
	#kink track cut
	isThereKinkTrack : boolean = true
	
	#number of kinked tracks cut
	#hasNumberofKinks : string = "2 2" //useful
	
	#1 track has 1 associated calo hit
	useEventTrackHasOneAssocCaloHit : boolean = true
	
	#charge cut
	useEventTrackHasCaloChargeAbove : boolean = true
	caloChargeMin_nVs = 0.5
	
	#parameters of elips for close to calib source vertex position cut
	#source_cut_ellipse_Y: 25.0 mm
        #source_cut_ellipse_Z: 30.0 mm 

# end
