[name="pipeline" type="dpp::chain_module"]
modules : string[2] = "SNCuts" "MiModule"

[name="flreconstruct.plugins" type="flreconstruct::section"]
plugins : string[2] = "SNCuts" "MiModule"
SNCuts.directory : string = "/sps/nemo/scratch/ayanko/software/INTEGRATE_calibration_cuts_module_TO_SNCuts/lib/"
MiModule.directory : string = "/sps/nemo/scratch/ayanko/software/MiModule/lib/"

[name="SNCuts" type="SNCuts"]  

	#useEventHasTwoNegativeParticles : boolean = true
  	#useEventHasTwoTracks : boolean = true
  	
  	useEventHasTwoFoilVertices : boolean = true
  	useEventHasTwoCaloHits : boolean = true
  	useEventHasTwoAssociatedCaloHits : boolean = true
  	useEventHasSumEnergyAbove : boolean = true
  	minSumEnergy : real = 0.0
  	useEventHasSumEnergyBelow : boolean = true
  	maxSumEnergy : real = 3500.0
		
	#number of kinked tracks cut
	hasNumberofKinks : string = "1 1"


[name="MiModule" type="MiModule"]

# end
